from odoo.exceptions import UserError


class WrongTypeError(UserError):
    pass